### ISSUE TITLE
Nuevas funciones

### ISSUE THREAD

**Issue by josemifd** [UNIZAR-30248-2024-EduPlanner/Frontend#12]
- [ ] getOrganizationByNIP
- [x] getCursoByNIP
- [ ] getAlumnoByNIP
- [ ] getProfesorByNIP

**Comment by bromfi24** [comment]
josemi tienes una funcion en organization.js

export const getUserIdByNIP = async (nip, organizationId) => {
    const { data, error } = await supabase
        .from('users')
        .select('id') // Solo seleccionamos el ID
        .eq('nip', nip)
        .eq('organization_id', organizationId) // Comprobar también por ID de organización
        .single(); // Devuelve solo un resultado

    if (error) {
        console.error("Error al obtener el ID de usuario:", error);
        return null; // En caso de error, devolver null
    }

    return data ? data.id : null; // Devuelve el ID o null si no se encuentra
};

que dado el nip y organizacion de un usuario te da el id

**Comment by bromfi24** [comment]
se me había olvidado comentartelo

**Comment by josemifd** [comment]
Cierro Issue tras haber realizado la función

getUserInfoByNIP
