### ISSUE TITLE
Funciones login

### ISSUE THREAD

**Issue by josemifd** [UNIZAR-30248-2024-EduPlanner/Frontend#13]
Las siguientes funciones que me corren más prisa son:

- [x] loginStudent
- [x] loginTeacher
- [x] registerStudent
- [x] registerTeacher
- [x] registerStudents??
- [x] registerTeachers??
- [x] registerCourses??

?? Estaría bien pensar en si es conveniente una función que automatice el insertar una lista de alumnos en vez de llamar muchas veces a registerStudent. Yo creo que sería más eficiente el tener una función que lo haga, pero decid qué opináis si creéis lo contrario.

**Comment by diemanane** [comment]
Hay login y register de usuario en general. Si fuera necesario crear despues de esto, me dice y las creo individuales
`// Función para iniciar sesión (login) de un usuario
export const loginUser = async (nip, pass, role, organization_id) => {
  const { data, error } = await supabase
    .from('users')
    .select('*')
    .eq('nip', nip)
    .eq('pass', pass)
    .eq('role', role)
    .eq('organization_id', organization_id)
    .single();
  if (error) {
    console.error("Error al iniciar sesión en el curso:", error);
    return false; // Error en la consulta
  }

  return !!data; // Devuelve true si hay datos (curso encontrado), false de lo contrario
};

// Función para registrar un nuevo curso
export const registerUser = async (name, nip, pass, role, organization_id) => {
  const { data, error } = await supabase
    .from('users')
    .insert([
      {
        name,
        nip,
        pass, // Almacena la contraseña de forma segura en producción
        role,
        organization_id, // Relación con la organización a la que pertenece
      },
    ]);

  return { data, error }; // Devuelve tanto 'data' como 'error' para una respuesta consistente
};`

**Comment by diemanane** [comment]
Para hacer un register de un usuario individual, se puede usar la funcion que se encuentra en src/supabase/user/user.js - registerUser, idem con el login. 

Para el registro de arrays, ya ha sido subido. 

Si se necesita login y register individual de teacher y student. Avisa. Si no, se puede dar por cerrada issue tras pruebas en frontend

**Comment by diemanane** [comment]
Esta hecho, mira si te sirve y dices
