### ISSUE TITLE
Otra funcion para login

### ISSUE THREAD

**Issue by LuisDanielGomez** [UNIZAR-30248-2024-EduPlanner/Frontend#16]
Como quedamos al final de añadir en la pantalla de inicio 2 botones para seleccionar el rol y la organización a los que se pretende acceder me hace falta un:

- [x] GetallOrganization() para obtener el nombre de todas las organizaciones y sus id. Asi pueden seleccionar la organización segun el nombre y se obtiene el organization_id que se manda en la funcion de loginUser

**Comment by diemanane** [comment]
Comentame si funciona correctamente. Si es asi, puedes cerrar issue
