### ISSUE TITLE
Duda relacionada con la diferencia entre los calendarios de estudiante y profesor.

### ISSUE THREAD

**Issue by bromfi24** [UNIZAR-30248-2024-EduPlanner/Frontend#25]
Hola!

¿Todos los profesores van a tener los mismos horarios que los estudiantes en un inicio?, ¿ O deberían fitrarse según que horarios de algún tipo, para el usuario profesor me refiero?  Y esto también se refiere a los eventos academicos que crea profesor, se deberían también ver en otros profesores relacionados con la asignatura o incluso, debería poder verlos el propio profesor?¿

**Comment by josemifd** [comment]
Los profesores van a tener los horarios de aquellas asignaturas a las que estén asociadas en un inicio.

Los eventos académicos que crea un profesor podrá verlos, editarlos y eliminarlos diría, así tendría sentido. Que lo vea todo el mundo asociado a esa asignatura y que solo puedan modificarlo los profesores

**Comment by bromfi24** [comment]
Perfecto, entendido!
